from __future__ import annotations

import csv
import datetime as dt
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any


SPOT_EXCHANGE_INFO_URL = "https://api.binance.com/api/v3/exchangeInfo"
USDM_EXCHANGE_INFO_URL = "https://fapi.binance.com/fapi/v1/exchangeInfo"

OUTPUT_DIR = Path(__file__).resolve().parent / "outputs"
SPOT_CSV = OUTPUT_DIR / "binance_tradifi_spot_symbols.csv"
FUTURES_CSV = OUTPUT_DIR / "binance_tradifi_futures_symbols.csv"
SUMMARY_JSON = OUTPUT_DIR / "binance_tradifi_symbols.json"
DEFAULT_LISTS_PY = OUTPUT_DIR / "binance_tradifi_default_symbols.py"


def fetch_json(url: str) -> dict[str, Any]:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def ms_to_datetime(value: Any) -> str:
    try:
        timestamp_ms = int(value)
    except (TypeError, ValueError):
        return ""
    if timestamp_ms <= 0:
        return ""
    return dt.datetime.fromtimestamp(timestamp_ms / 1000, tz=dt.timezone.utc).isoformat()


def bool_field(value: Any) -> bool:
    return bool(value) if isinstance(value, bool) else str(value).lower() == "true"


def get_tradifi_futures(usdm_info: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in usdm_info.get("symbols", []):
        if item.get("contractType") != "TRADIFI_PERPETUAL":
            continue
        if item.get("status") != "TRADING":
            continue

        rows.append(
            {
                "symbol": item.get("symbol", ""),
                "base_asset": item.get("baseAsset", ""),
                "quote_asset": item.get("quoteAsset", ""),
                "margin_asset": item.get("marginAsset", ""),
                "contract_type": item.get("contractType", ""),
                "status": item.get("status", ""),
                "onboard_time_utc": ms_to_datetime(item.get("onboardDate")),
                "order_types": "|".join(item.get("orderTypes", []) or []),
                "time_in_force": "|".join(item.get("timeInForce", []) or []),
            }
        )

    return sorted(rows, key=lambda row: row["symbol"])


def get_tradifi_spot(spot_info: dict[str, Any], tradifi_bases: set[str]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in spot_info.get("symbols", []):
        symbol = str(item.get("symbol", ""))
        base_asset = str(item.get("baseAsset", ""))
        quote_asset = str(item.get("quoteAsset", ""))
        status = item.get("status", "")
        is_spot_allowed = bool_field(item.get("isSpotTradingAllowed"))

        if status != "TRADING" or not is_spot_allowed:
            continue
        if quote_asset != "USDT":
            continue

        if base_asset in tradifi_bases:
            underlying = base_asset
            match_type = "exact"
        elif base_asset.endswith("B") and base_asset[:-1] in tradifi_bases:
            underlying = base_asset[:-1]
            match_type = "b_suffix"
        else:
            continue

        rows.append(
            {
                "symbol": symbol,
                "base_asset": base_asset,
                "underlying": underlying,
                "match_type": match_type,
                "quote_asset": quote_asset,
                "status": status,
                "is_spot_trading_allowed": is_spot_allowed,
                "is_margin_trading_allowed": bool_field(item.get("isMarginTradingAllowed")),
                "order_types": "|".join(item.get("orderTypes", []) or []),
            }
        )

    return sorted(rows, key=lambda row: row["symbol"])


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if rows:
        fieldnames = list(rows[0].keys())
    else:
        fieldnames = ["symbol"]
    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def python_list(name: str, values: list[str]) -> str:
    lines = [f"{name} = ["]
    lines.extend(f'    "{value}",' for value in values)
    lines.append("]")
    return "\n".join(lines)


def write_default_lists(path: Path, spot_rows: list[dict[str, Any]], futures_rows: list[dict[str, Any]]) -> None:
    spot_symbols = [row["symbol"] for row in spot_rows]
    futures_symbols = [row["symbol"] for row in futures_rows]
    spot_bases = [row["underlying"].lower() for row in spot_rows]
    futures_bases = [row["base_asset"].lower() for row in futures_rows]

    content = "\n\n".join(
        [
            "# Generated by fetch_binance_tradifi_symbols.py",
            python_list("TRADIFI_SPOT_SYMBOLS", spot_symbols),
            python_list("TRADIFI_FUTURES_SYMBOLS", futures_symbols),
            python_list("TRADIFI_SPOT_BASES", spot_bases),
            python_list("TRADIFI_FUTURES_BASES", futures_bases),
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    now = dt.datetime.now(dt.timezone.utc).astimezone().isoformat(timespec="seconds")
    usdm_info = fetch_json(USDM_EXCHANGE_INFO_URL)
    futures_rows = get_tradifi_futures(usdm_info)
    futures_bases = {row["base_asset"] for row in futures_rows}

    spot_info = fetch_json(SPOT_EXCHANGE_INFO_URL)
    spot_rows = get_tradifi_spot(spot_info, futures_bases)

    write_csv(FUTURES_CSV, futures_rows)
    write_csv(SPOT_CSV, spot_rows)
    write_default_lists(DEFAULT_LISTS_PY, spot_rows, futures_rows)

    summary = {
        "generated_at": now,
        "source": {
            "spot": SPOT_EXCHANGE_INFO_URL,
            "usdm": USDM_EXCHANGE_INFO_URL,
        },
        "filters": {
            "spot": "status=TRADING, isSpotTradingAllowed=true, quoteAsset=USDT, baseAsset equals a TRADIFI_PERPETUAL base or baseAsset endswith B and underlying exists in TRADIFI_PERPETUAL bases",
            "futures": "contractType=TRADIFI_PERPETUAL, status=TRADING",
        },
        "spot_count": len(spot_rows),
        "futures_count": len(futures_rows),
        "spot_symbols": [row["symbol"] for row in spot_rows],
        "futures_symbols": [row["symbol"] for row in futures_rows],
    }
    SUMMARY_JSON.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"spot_count={len(spot_rows)}")
    print(f"futures_count={len(futures_rows)}")
    print(f"wrote {SPOT_CSV.name}")
    print(f"wrote {FUTURES_CSV.name}")
    print(f"wrote {SUMMARY_JSON.name}")
    print(f"wrote {DEFAULT_LISTS_PY.name}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise
